# Generated by Django 4.1.3 on 2022-12-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="product_images"
            ),
        ),
    ]
